# Generated by Django 4.1.1 on 2022-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcogol',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(height_field=200, upload_to='media/%Y/%m/%d', width_field=200),
        ),
    ]
