# Generated by Django 4.1.1 on 2022-09-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0002_beer_alcogol_alter_beer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='country',
        ),
    ]
