# Generated by Django 4.1.1 on 2022-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0003_remove_beer_category_remove_beer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='alcogol',
            field=models.FloatField(default=5),
        ),
    ]
