# Generated by Django 4.1.1 on 2022-09-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0004_alter_beer_alcogol'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingbeer.category'),
        ),
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingbeer.country'),
        ),
    ]
