# Generated by Django 4.1.1 on 2022-10-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0005_profile_rang_delete_userprofile_profile_rang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/Guts.jpg', upload_to='images/profile/'),
        ),
    ]
