# Generated by Django 4.1.1 on 2022-10-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbeer', '0010_alter_comment_content_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ratingbeer.beer'),
        ),
    ]
